# Generated by Django 3.0.6 on 2020-06-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('HouseType', models.CharField(choices=[('Single', 'Single Family'), ('Condo', 'Condo'), ('Top', 'Top Tier'), ('Middle', 'Middle Tier'), ('Bottom', 'Bottom Tier'), ('Studio', 'Studio'), ('One', 'One Bed'), ('Two', 'Two Bed'), ('Three', 'Three Bed'), ('Four', 'Four Bed'), ('Many', 'Many Bed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingDate', models.DateField()),
                ('Price', models.IntegerField()),
                ('houseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.House')),
            ],
        ),
    ]
