# Generated by Django 3.0.6 on 2020-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseId', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('HouseType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceId', models.IntegerField()),
                ('houseId', models.IntegerField()),
                ('listingDate', models.DateTimeField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
