# Generated by Django 3.0.6 on 2020-06-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('HouseType', models.CharField(choices=[('All Homes', 'All Homes'), ('Single Family', 'Single Family'), ('Condo Condo', 'Condo'), ('Top Tier', 'Top Tier'), ('Middle Tier', 'Middle Tier'), ('Bottom Tier', 'Bottom Tier'), ('Studio', 'Studio'), ('One Bed', 'One Bed'), ('Two Bed', 'Two Bed'), ('Three Bed', 'Three Bed'), ('Four Four', 'Four Bed'), ('Many Four', 'Many Bed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingDate', models.DateField()),
                ('Price', models.IntegerField()),
                ('houseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.House')),
            ],
        ),
    ]
