# Generated by Django 3.0.6 on 2020-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='HouseType',
            field=models.CharField(choices=[('Single', 'Single Family'), ('Condo', 'Condo'), ('Top', 'Top Tier'), ('Middle', 'Middle Tier'), ('Bottom', 'Bottom Tier'), ('Studio', 'Studio'), ('One', 'One Bed'), ('Two', 'Two Bed'), ('Three', 'Three Bed'), ('Four', 'Four Bed'), ('Many', 'Many Bed')], max_length=100),
        ),
    ]
